/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

angular.module('HealthOSLib', [])
    .factory('Configuration', [function() {
        return {
            //The base Uri for API calls
            BASEURI : "http://{{0}}/api/v1",

            //TODO: Replace the host with an appropriate value
            host : "TODO: Replace",

            //The OAuth 2.0 access token to be set before API calls
            //TODO: Replace the oAuthAccessToken with an appropriate value
            oAuthAccessToken : "TODO: Replace"

        };
    }
]);

}(angular));
