/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of AllDiseasesResponse
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('AllDiseasesResponse', ['BaseModel',
        function (BaseModel) {
            var AllDiseasesResponse = function (obj) {
                if (!obj) {
                    this.diseaseName = null;
                    this.diseaseCat = null;
                    this.diseaseInfo = null;
                    this.diseaseId = null;
        
                    // Append to variable dictionary
                    this._variableDict['diseaseName'] = 'disease_name';
                    this._variableDict['diseaseCat'] = 'disease_cat';
                    this._variableDict['diseaseInfo'] = 'disease_info';
                    this._variableDict['diseaseId'] = 'disease_id';
                } else {
                    this.diseaseName = obj.disease_name;
                    this.diseaseCat = obj.disease_cat;
                    this.diseaseInfo = obj.disease_info;
                    this.diseaseId = obj.disease_id;
            
                    // Append to variable dictionary
                    this._variableDict['diseaseName'] = 'disease_name';
                    this._variableDict['diseaseCat'] = 'disease_cat';
                    this._variableDict['diseaseInfo'] = 'disease_info';
                    this._variableDict['diseaseId'] = 'disease_id';
                }
            }
    
            AllDiseasesResponse.prototype = new BaseModel();
            AllDiseasesResponse.prototype.constructor = AllDiseasesResponse;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            AllDiseasesResponse.prototype.getDiseaseName = function () {
                return this.diseaseName;
            };
        
            /**
             * Setter for DiseaseName
             * 
             * @param {string} value 
             */
            AllDiseasesResponse.prototype.setDiseaseName = function (value) {
                this.diseaseName = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            AllDiseasesResponse.prototype.getDiseaseCat = function () {
                return this.diseaseCat;
            };
        
            /**
             * Setter for DiseaseCat
             * 
             * @param {string} value 
             */
            AllDiseasesResponse.prototype.setDiseaseCat = function (value) {
                this.diseaseCat = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            AllDiseasesResponse.prototype.getDiseaseInfo = function () {
                return this.diseaseInfo;
            };
        
            /**
             * Setter for DiseaseInfo
             * 
             * @param {string} value 
             */
            AllDiseasesResponse.prototype.setDiseaseInfo = function (value) {
                this.diseaseInfo = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            AllDiseasesResponse.prototype.getDiseaseId = function () {
                return this.diseaseId;
            };
        
            /**
             * Setter for DiseaseId
             * 
             * @param {string} value 
             */
            AllDiseasesResponse.prototype.setDiseaseId = function (value) {
                this.diseaseId = value;
            };
        
            return AllDiseasesResponse;
        }
    ]);

}(angular));
