/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of AllFoodRestaurantsResponse
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('AllFoodRestaurantsResponse', ['BaseModel',
        function (BaseModel) {
            var AllFoodRestaurantsResponse = function (obj) {
                if (!obj) {
                    this.restaurantName = null;
                    this.foodRestaurantId = null;
        
                    // Append to variable dictionary
                    this._variableDict['restaurantName'] = 'restaurant_name';
                    this._variableDict['foodRestaurantId'] = 'food_restaurant_id';
                } else {
                    this.restaurantName = obj.restaurant_name;
                    this.foodRestaurantId = obj.food_restaurant_id;
            
                    // Append to variable dictionary
                    this._variableDict['restaurantName'] = 'restaurant_name';
                    this._variableDict['foodRestaurantId'] = 'food_restaurant_id';
                }
            }
    
            AllFoodRestaurantsResponse.prototype = new BaseModel();
            AllFoodRestaurantsResponse.prototype.constructor = AllFoodRestaurantsResponse;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            AllFoodRestaurantsResponse.prototype.getRestaurantName = function () {
                return this.restaurantName;
            };
        
            /**
             * Setter for RestaurantName
             * 
             * @param {string} value 
             */
            AllFoodRestaurantsResponse.prototype.setRestaurantName = function (value) {
                this.restaurantName = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            AllFoodRestaurantsResponse.prototype.getFoodRestaurantId = function () {
                return this.foodRestaurantId;
            };
        
            /**
             * Setter for FoodRestaurantId
             * 
             * @param {string} value 
             */
            AllFoodRestaurantsResponse.prototype.setFoodRestaurantId = function (value) {
                this.foodRestaurantId = value;
            };
        
            return AllFoodRestaurantsResponse;
        }
    ]);

}(angular));
