/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of AllLabTestsResponse
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('AllLabTestsResponse', ['BaseModel', 'LabTestData34',
        function (BaseModel, LabTestData34) {
            var AllLabTestsResponse = function (obj) {
                if (!obj) {
                    this.labTestName = null;
                    this.alternateName = null;
                    this.labTestId = null;
                    this.labTestData = null;
        
                    // Append to variable dictionary
                    this._variableDict['labTestName'] = 'lab_test_name';
                    this._variableDict['alternateName'] = 'alternate_name';
                    this._variableDict['labTestId'] = 'lab_test_id';
                    this._variableDict['labTestData'] = 'lab_test_data';
                } else {
                    this.labTestName = obj.lab_test_name;
                    this.alternateName = obj.alternate_name;
                    this.labTestId = obj.lab_test_id;
                    this.labTestData = new LabTestData34(obj.lab_test_data);
            
                    // Append to variable dictionary
                    this._variableDict['labTestName'] = 'lab_test_name';
                    this._variableDict['alternateName'] = 'alternate_name';
                    this._variableDict['labTestId'] = 'lab_test_id';
                    this._variableDict['labTestData'] = 'lab_test_data';
                }
            }
    
            AllLabTestsResponse.prototype = new BaseModel();
            AllLabTestsResponse.prototype.constructor = AllLabTestsResponse;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            AllLabTestsResponse.prototype.getLabTestName = function () {
                return this.labTestName;
            };
        
            /**
             * Setter for LabTestName
             * 
             * @param {string} value 
             */
            AllLabTestsResponse.prototype.setLabTestName = function (value) {
                this.labTestName = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            AllLabTestsResponse.prototype.getAlternateName = function () {
                return this.alternateName;
            };
        
            /**
             * Setter for AlternateName
             * 
             * @param {string} value 
             */
            AllLabTestsResponse.prototype.setAlternateName = function (value) {
                this.alternateName = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            AllLabTestsResponse.prototype.getLabTestId = function () {
                return this.labTestId;
            };
        
            /**
             * Setter for LabTestId
             * 
             * @param {string} value 
             */
            AllLabTestsResponse.prototype.setLabTestId = function (value) {
                this.labTestId = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {LabTestData34}
             */
            AllLabTestsResponse.prototype.getLabTestData = function () {
                return this.labTestData;
            };
        
            /**
             * Setter for LabTestData
             * 
             * @param {LabTestData34} value 
             */
            AllLabTestsResponse.prototype.setLabTestData = function (value) {
                this.labTestData = value;
            };
        
            return AllLabTestsResponse;
        }
    ]);

}(angular));
