/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Constituent
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('Constituent', ['BaseModel',
        function (BaseModel) {
            var Constituent = function (obj) {
                if (!obj) {
                    this.name = null;
                    this.strength = null;
                } else {
                    this.name = obj.name;
                    this.strength = obj.strength;
                }
            }
    
            Constituent.prototype = new BaseModel();
            Constituent.prototype.constructor = Constituent;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            Constituent.prototype.getName = function () {
                return this.name;
            };
        
            /**
             * Setter for Name
             * 
             * @param {string} value 
             */
            Constituent.prototype.setName = function (value) {
                this.name = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            Constituent.prototype.getStrength = function () {
                return this.strength;
            };
        
            /**
             * Setter for Strength
             * 
             * @param {string} value 
             */
            Constituent.prototype.setStrength = function (value) {
                this.strength = value;
            };
        
            return Constituent;
        }
    ]);

}(angular));
