/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ExercisesResponse
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('ExercisesResponse', ['BaseModel',
        function (BaseModel) {
            var ExercisesResponse = function (obj) {
                if (!obj) {
                    this.name = null;
                    this.category = null;
                    this.caloryCount = null;
                    this.cardioSubcategory = null;
                    this.primaryMuscleGroup = null;
                    this.exerciseId = null;
                    this.searchScore = null;
        
                    // Append to variable dictionary
                    this._variableDict['caloryCount'] = 'calory_count';
                    this._variableDict['cardioSubcategory'] = 'cardio_subcategory';
                    this._variableDict['primaryMuscleGroup'] = 'primary_muscle_group';
                    this._variableDict['exerciseId'] = 'exercise_id';
                    this._variableDict['searchScore'] = 'search_score';
                } else {
                    this.name = obj.name;
                    this.category = obj.category;
                    this.caloryCount = obj.calory_count;
                    this.cardioSubcategory = obj.cardio_subcategory;
                    this.primaryMuscleGroup = obj.primary_muscle_group;
                    this.exerciseId = obj.exercise_id;
                    this.searchScore = obj.search_score;
            
                    // Append to variable dictionary
                    this._variableDict['caloryCount'] = 'calory_count';
                    this._variableDict['cardioSubcategory'] = 'cardio_subcategory';
                    this._variableDict['primaryMuscleGroup'] = 'primary_muscle_group';
                    this._variableDict['exerciseId'] = 'exercise_id';
                    this._variableDict['searchScore'] = 'search_score';
                }
            }
    
            ExercisesResponse.prototype = new BaseModel();
            ExercisesResponse.prototype.constructor = ExercisesResponse;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            ExercisesResponse.prototype.getName = function () {
                return this.name;
            };
        
            /**
             * Setter for Name
             * 
             * @param {string} value 
             */
            ExercisesResponse.prototype.setName = function (value) {
                this.name = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            ExercisesResponse.prototype.getCategory = function () {
                return this.category;
            };
        
            /**
             * Setter for Category
             * 
             * @param {string} value 
             */
            ExercisesResponse.prototype.setCategory = function (value) {
                this.category = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            ExercisesResponse.prototype.getCaloryCount = function () {
                return this.caloryCount;
            };
        
            /**
             * Setter for CaloryCount
             * 
             * @param {string} value 
             */
            ExercisesResponse.prototype.setCaloryCount = function (value) {
                this.caloryCount = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            ExercisesResponse.prototype.getCardioSubcategory = function () {
                return this.cardioSubcategory;
            };
        
            /**
             * Setter for CardioSubcategory
             * 
             * @param {string} value 
             */
            ExercisesResponse.prototype.setCardioSubcategory = function (value) {
                this.cardioSubcategory = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            ExercisesResponse.prototype.getPrimaryMuscleGroup = function () {
                return this.primaryMuscleGroup;
            };
        
            /**
             * Setter for PrimaryMuscleGroup
             * 
             * @param {string} value 
             */
            ExercisesResponse.prototype.setPrimaryMuscleGroup = function (value) {
                this.primaryMuscleGroup = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            ExercisesResponse.prototype.getExerciseId = function () {
                return this.exerciseId;
            };
        
            /**
             * Setter for ExerciseId
             * 
             * @param {string} value 
             */
            ExercisesResponse.prototype.setExerciseId = function (value) {
                this.exerciseId = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {double}
             */
            ExercisesResponse.prototype.getSearchScore = function () {
                return this.searchScore;
            };
        
            /**
             * Setter for SearchScore
             * 
             * @param {double} value 
             */
            ExercisesResponse.prototype.setSearchScore = function (value) {
                this.searchScore = value;
            };
        
            return ExercisesResponse;
        }
    ]);

}(angular));
