/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of GenericsResponse
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('GenericsResponse', ['BaseModel',
        function (BaseModel) {
            var GenericsResponse = function (obj) {
                if (!obj) {
                    this.name = null;
                    this.genericId = null;
                    this.theraupticUses = null;
                    this.searchScore = null;
        
                    // Append to variable dictionary
                    this._variableDict['genericId'] = 'generic_id';
                    this._variableDict['theraupticUses'] = 'therauptic_uses';
                    this._variableDict['searchScore'] = 'search_score';
                } else {
                    this.name = obj.name;
                    this.genericId = obj.generic_id;
                    this.theraupticUses = obj.therauptic_uses;
                    this.searchScore = obj.search_score;
            
                    // Append to variable dictionary
                    this._variableDict['genericId'] = 'generic_id';
                    this._variableDict['theraupticUses'] = 'therauptic_uses';
                    this._variableDict['searchScore'] = 'search_score';
                }
            }
    
            GenericsResponse.prototype = new BaseModel();
            GenericsResponse.prototype.constructor = GenericsResponse;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            GenericsResponse.prototype.getName = function () {
                return this.name;
            };
        
            /**
             * Setter for Name
             * 
             * @param {string} value 
             */
            GenericsResponse.prototype.setName = function (value) {
                this.name = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            GenericsResponse.prototype.getGenericId = function () {
                return this.genericId;
            };
        
            /**
             * Setter for GenericId
             * 
             * @param {string} value 
             */
            GenericsResponse.prototype.setGenericId = function (value) {
                this.genericId = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {array}
             */
            GenericsResponse.prototype.getTheraupticUses = function () {
                return this.theraupticUses;
            };
        
            /**
             * Setter for TheraupticUses
             * 
             * @param {array} value 
             */
            GenericsResponse.prototype.setTheraupticUses = function (value) {
                this.theraupticUses = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {double}
             */
            GenericsResponse.prototype.getSearchScore = function () {
                return this.searchScore;
            };
        
            /**
             * Setter for SearchScore
             * 
             * @param {double} value 
             */
            GenericsResponse.prototype.setSearchScore = function (value) {
                this.searchScore = value;
            };
        
            return GenericsResponse;
        }
    ]);

}(angular));
