/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Interaction
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('Interaction', ['BaseModel', 'Item',
        function (BaseModel, Item) {
            var Interaction = function (obj) {
                if (!obj) {
                    this.items = null;
                    this.severity = null;
                    this.description = null;
                    this.source = null;
                } else {
                    this.items = obj.items.map(function (model) {
                        return new Item(model);
                    });
                    this.severity = obj.severity;
                    this.description = obj.description;
                    this.source = obj.source;
                }
            }
    
            Interaction.prototype = new BaseModel();
            Interaction.prototype.constructor = Interaction;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {array}
             */
            Interaction.prototype.getItems = function () {
                return this.items;
            };
        
            /**
             * Setter for Items
             * 
             * @param {array} value 
             */
            Interaction.prototype.setItems = function (value) {
                this.items = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            Interaction.prototype.getSeverity = function () {
                return this.severity;
            };
        
            /**
             * Setter for Severity
             * 
             * @param {string} value 
             */
            Interaction.prototype.setSeverity = function (value) {
                this.severity = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            Interaction.prototype.getDescription = function () {
                return this.description;
            };
        
            /**
             * Setter for Description
             * 
             * @param {string} value 
             */
            Interaction.prototype.setDescription = function (value) {
                this.description = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            Interaction.prototype.getSource = function () {
                return this.source;
            };
        
            /**
             * Setter for Source
             * 
             * @param {string} value 
             */
            Interaction.prototype.setSource = function (value) {
                this.source = value;
            };
        
            return Interaction;
        }
    ]);

}(angular));
