/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Item
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('Item', ['BaseModel',
        function (BaseModel) {
            var Item = function (obj) {
                if (!obj) {
                    this.name = null;
                } else {
                    this.name = obj.name;
                }
            }
    
            Item.prototype = new BaseModel();
            Item.prototype.constructor = Item;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            Item.prototype.getName = function () {
                return this.name;
            };
        
            /**
             * Setter for Name
             * 
             * @param {string} value 
             */
            Item.prototype.setName = function (value) {
                this.name = value;
            };
        
            return Item;
        }
    ]);

}(angular));
