/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of LabTestData34
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('LabTestData34', ['BaseModel',
        function (BaseModel) {
            var LabTestData34 = function (obj) {
                if (!obj) {
                    this.orderingInformation = null;
                    this.laboratory = null;
                    this.testCode = null;
                    this.specimenTypes = null;
                    this.containerTypes = null;
                    this.collectionInstructions = null;
                    this.frequency = null;
        
                    // Append to variable dictionary
                    this._variableDict['orderingInformation'] = 'Ordering information';
                    this._variableDict['laboratory'] = 'Laboratory';
                    this._variableDict['testCode'] = 'Test Code';
                    this._variableDict['specimenTypes'] = 'Specimen types';
                    this._variableDict['containerTypes'] = 'Container types';
                    this._variableDict['collectionInstructions'] = 'Collection Instructions';
                    this._variableDict['frequency'] = 'Frequency';
                } else {
                    this.orderingInformation = obj.Ordering information;
                    this.laboratory = obj.Laboratory;
                    this.testCode = obj.Test Code;
                    this.specimenTypes = obj.Specimen types;
                    this.containerTypes = obj.Container types;
                    this.collectionInstructions = obj.Collection Instructions;
                    this.frequency = obj.Frequency;
            
                    // Append to variable dictionary
                    this._variableDict['orderingInformation'] = 'Ordering information';
                    this._variableDict['laboratory'] = 'Laboratory';
                    this._variableDict['testCode'] = 'Test Code';
                    this._variableDict['specimenTypes'] = 'Specimen types';
                    this._variableDict['containerTypes'] = 'Container types';
                    this._variableDict['collectionInstructions'] = 'Collection Instructions';
                    this._variableDict['frequency'] = 'Frequency';
                }
            }
    
            LabTestData34.prototype = new BaseModel();
            LabTestData34.prototype.constructor = LabTestData34;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            LabTestData34.prototype.getOrderingInformation = function () {
                return this.orderingInformation;
            };
        
            /**
             * Setter for OrderingInformation
             * 
             * @param {string} value 
             */
            LabTestData34.prototype.setOrderingInformation = function (value) {
                this.orderingInformation = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            LabTestData34.prototype.getLaboratory = function () {
                return this.laboratory;
            };
        
            /**
             * Setter for Laboratory
             * 
             * @param {string} value 
             */
            LabTestData34.prototype.setLaboratory = function (value) {
                this.laboratory = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            LabTestData34.prototype.getTestCode = function () {
                return this.testCode;
            };
        
            /**
             * Setter for TestCode
             * 
             * @param {string} value 
             */
            LabTestData34.prototype.setTestCode = function (value) {
                this.testCode = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            LabTestData34.prototype.getSpecimenTypes = function () {
                return this.specimenTypes;
            };
        
            /**
             * Setter for SpecimenTypes
             * 
             * @param {string} value 
             */
            LabTestData34.prototype.setSpecimenTypes = function (value) {
                this.specimenTypes = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            LabTestData34.prototype.getContainerTypes = function () {
                return this.containerTypes;
            };
        
            /**
             * Setter for ContainerTypes
             * 
             * @param {string} value 
             */
            LabTestData34.prototype.setContainerTypes = function (value) {
                this.containerTypes = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            LabTestData34.prototype.getCollectionInstructions = function () {
                return this.collectionInstructions;
            };
        
            /**
             * Setter for CollectionInstructions
             * 
             * @param {string} value 
             */
            LabTestData34.prototype.setCollectionInstructions = function (value) {
                this.collectionInstructions = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            LabTestData34.prototype.getFrequency = function () {
                return this.frequency;
            };
        
            /**
             * Setter for Frequency
             * 
             * @param {string} value 
             */
            LabTestData34.prototype.setFrequency = function (value) {
                this.frequency = value;
            };
        
            return LabTestData34;
        }
    ]);

}(angular));
