/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of MedicineInteractionsResponse
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('MedicineInteractionsResponse', ['BaseModel', 'Interaction',
        function (BaseModel, Interaction) {
            var MedicineInteractionsResponse = function (obj) {
                if (!obj) {
                    this.generic = null;
                    this.interactions = null;
                } else {
                    this.generic = obj.generic;
                    this.interactions = obj.interactions.map(function (model) {
                        return new Interaction(model);
                    });
                }
            }
    
            MedicineInteractionsResponse.prototype = new BaseModel();
            MedicineInteractionsResponse.prototype.constructor = MedicineInteractionsResponse;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            MedicineInteractionsResponse.prototype.getGeneric = function () {
                return this.generic;
            };
        
            /**
             * Setter for Generic
             * 
             * @param {string} value 
             */
            MedicineInteractionsResponse.prototype.setGeneric = function (value) {
                this.generic = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {array}
             */
            MedicineInteractionsResponse.prototype.getInteractions = function () {
                return this.interactions;
            };
        
            /**
             * Setter for Interactions
             * 
             * @param {array} value 
             */
            MedicineInteractionsResponse.prototype.setInteractions = function (value) {
                this.interactions = value;
            };
        
            return MedicineInteractionsResponse;
        }
    ]);

}(angular));
