/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of MedicinesResponse
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('MedicinesResponse', ['BaseModel', 'Constituent', 'Schedule',
        function (BaseModel, Constituent, Schedule) {
            var MedicinesResponse = function (obj) {
                if (!obj) {
                    this.name = null;
                    this.form = null;
                    this.standardUnits = null;
                    this.packageForm = null;
                    this.price = null;
                    this.size = null;
                    this.manufacturer = null;
                    this.constituents = null;
                    this.schedule = null;
                    this.id = null;
                    this.medicineId = null;
                    this.searchScore = null;
        
                    // Append to variable dictionary
                    this._variableDict['medicineId'] = 'medicine_id';
                    this._variableDict['searchScore'] = 'search_score';
                } else {
                    this.name = obj.name;
                    this.form = obj.form;
                    this.standardUnits = obj.standardUnits;
                    this.packageForm = obj.packageForm;
                    this.price = obj.price;
                    this.size = obj.size;
                    this.manufacturer = obj.manufacturer;
                    this.constituents = obj.constituents.map(function (model) {
                        return new Constituent(model);
                    });
                    this.schedule = new Schedule(obj.schedule);
                    this.id = obj.id;
                    this.medicineId = obj.medicine_id;
                    this.searchScore = obj.search_score;
            
                    // Append to variable dictionary
                    this._variableDict['medicineId'] = 'medicine_id';
                    this._variableDict['searchScore'] = 'search_score';
                }
            }
    
            MedicinesResponse.prototype = new BaseModel();
            MedicinesResponse.prototype.constructor = MedicinesResponse;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            MedicinesResponse.prototype.getName = function () {
                return this.name;
            };
        
            /**
             * Setter for Name
             * 
             * @param {string} value 
             */
            MedicinesResponse.prototype.setName = function (value) {
                this.name = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            MedicinesResponse.prototype.getForm = function () {
                return this.form;
            };
        
            /**
             * Setter for Form
             * 
             * @param {string} value 
             */
            MedicinesResponse.prototype.setForm = function (value) {
                this.form = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {int}
             */
            MedicinesResponse.prototype.getStandardUnits = function () {
                return this.standardUnits;
            };
        
            /**
             * Setter for StandardUnits
             * 
             * @param {int} value 
             */
            MedicinesResponse.prototype.setStandardUnits = function (value) {
                this.standardUnits = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            MedicinesResponse.prototype.getPackageForm = function () {
                return this.packageForm;
            };
        
            /**
             * Setter for PackageForm
             * 
             * @param {string} value 
             */
            MedicinesResponse.prototype.setPackageForm = function (value) {
                this.packageForm = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {double}
             */
            MedicinesResponse.prototype.getPrice = function () {
                return this.price;
            };
        
            /**
             * Setter for Price
             * 
             * @param {double} value 
             */
            MedicinesResponse.prototype.setPrice = function (value) {
                this.price = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            MedicinesResponse.prototype.getSize = function () {
                return this.size;
            };
        
            /**
             * Setter for Size
             * 
             * @param {string} value 
             */
            MedicinesResponse.prototype.setSize = function (value) {
                this.size = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            MedicinesResponse.prototype.getManufacturer = function () {
                return this.manufacturer;
            };
        
            /**
             * Setter for Manufacturer
             * 
             * @param {string} value 
             */
            MedicinesResponse.prototype.setManufacturer = function (value) {
                this.manufacturer = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {array}
             */
            MedicinesResponse.prototype.getConstituents = function () {
                return this.constituents;
            };
        
            /**
             * Setter for Constituents
             * 
             * @param {array} value 
             */
            MedicinesResponse.prototype.setConstituents = function (value) {
                this.constituents = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {Schedule}
             */
            MedicinesResponse.prototype.getSchedule = function () {
                return this.schedule;
            };
        
            /**
             * Setter for Schedule
             * 
             * @param {Schedule} value 
             */
            MedicinesResponse.prototype.setSchedule = function (value) {
                this.schedule = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            MedicinesResponse.prototype.getId = function () {
                return this.id;
            };
        
            /**
             * Setter for Id
             * 
             * @param {string} value 
             */
            MedicinesResponse.prototype.setId = function (value) {
                this.id = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            MedicinesResponse.prototype.getMedicineId = function () {
                return this.medicineId;
            };
        
            /**
             * Setter for MedicineId
             * 
             * @param {string} value 
             */
            MedicinesResponse.prototype.setMedicineId = function (value) {
                this.medicineId = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {double}
             */
            MedicinesResponse.prototype.getSearchScore = function () {
                return this.searchScore;
            };
        
            /**
             * Setter for SearchScore
             * 
             * @param {double} value 
             */
            MedicinesResponse.prototype.setSearchScore = function (value) {
                this.searchScore = value;
            };
        
            return MedicinesResponse;
        }
    ]);

}(angular));
