/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SearchDiseasesResponse
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('SearchDiseasesResponse', ['BaseModel',
        function (BaseModel) {
            var SearchDiseasesResponse = function (obj) {
                if (!obj) {
                    this.diseaseName = null;
                    this.diseaseCat = null;
                    this.diseaseInfo = null;
                    this.diseaseId = null;
                    this.searchScore = null;
        
                    // Append to variable dictionary
                    this._variableDict['diseaseName'] = 'disease_name';
                    this._variableDict['diseaseCat'] = 'disease_cat';
                    this._variableDict['diseaseInfo'] = 'disease_info';
                    this._variableDict['diseaseId'] = 'disease_id';
                    this._variableDict['searchScore'] = 'search_score';
                } else {
                    this.diseaseName = obj.disease_name;
                    this.diseaseCat = obj.disease_cat;
                    this.diseaseInfo = obj.disease_info;
                    this.diseaseId = obj.disease_id;
                    this.searchScore = obj.search_score;
            
                    // Append to variable dictionary
                    this._variableDict['diseaseName'] = 'disease_name';
                    this._variableDict['diseaseCat'] = 'disease_cat';
                    this._variableDict['diseaseInfo'] = 'disease_info';
                    this._variableDict['diseaseId'] = 'disease_id';
                    this._variableDict['searchScore'] = 'search_score';
                }
            }
    
            SearchDiseasesResponse.prototype = new BaseModel();
            SearchDiseasesResponse.prototype.constructor = SearchDiseasesResponse;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            SearchDiseasesResponse.prototype.getDiseaseName = function () {
                return this.diseaseName;
            };
        
            /**
             * Setter for DiseaseName
             * 
             * @param {string} value 
             */
            SearchDiseasesResponse.prototype.setDiseaseName = function (value) {
                this.diseaseName = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            SearchDiseasesResponse.prototype.getDiseaseCat = function () {
                return this.diseaseCat;
            };
        
            /**
             * Setter for DiseaseCat
             * 
             * @param {string} value 
             */
            SearchDiseasesResponse.prototype.setDiseaseCat = function (value) {
                this.diseaseCat = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            SearchDiseasesResponse.prototype.getDiseaseInfo = function () {
                return this.diseaseInfo;
            };
        
            /**
             * Setter for DiseaseInfo
             * 
             * @param {string} value 
             */
            SearchDiseasesResponse.prototype.setDiseaseInfo = function (value) {
                this.diseaseInfo = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            SearchDiseasesResponse.prototype.getDiseaseId = function () {
                return this.diseaseId;
            };
        
            /**
             * Setter for DiseaseId
             * 
             * @param {string} value 
             */
            SearchDiseasesResponse.prototype.setDiseaseId = function (value) {
                this.diseaseId = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {double}
             */
            SearchDiseasesResponse.prototype.getSearchScore = function () {
                return this.searchScore;
            };
        
            /**
             * Setter for SearchScore
             * 
             * @param {double} value 
             */
            SearchDiseasesResponse.prototype.setSearchScore = function (value) {
                this.searchScore = value;
            };
        
            return SearchDiseasesResponse;
        }
    ]);

}(angular));
