/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SearchFoodRestaurantsResponse
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('SearchFoodRestaurantsResponse', ['BaseModel',
        function (BaseModel) {
            var SearchFoodRestaurantsResponse = function (obj) {
                if (!obj) {
                    this.logo = null;
                    this.name = null;
                    this.foodRestaurantId = null;
                    this.searchScore = null;
        
                    // Append to variable dictionary
                    this._variableDict['foodRestaurantId'] = 'food_restaurant_id';
                    this._variableDict['searchScore'] = 'search_score';
                } else {
                    this.logo = obj.logo;
                    this.name = obj.name;
                    this.foodRestaurantId = obj.food_restaurant_id;
                    this.searchScore = obj.search_score;
            
                    // Append to variable dictionary
                    this._variableDict['foodRestaurantId'] = 'food_restaurant_id';
                    this._variableDict['searchScore'] = 'search_score';
                }
            }
    
            SearchFoodRestaurantsResponse.prototype = new BaseModel();
            SearchFoodRestaurantsResponse.prototype.constructor = SearchFoodRestaurantsResponse;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            SearchFoodRestaurantsResponse.prototype.getLogo = function () {
                return this.logo;
            };
        
            /**
             * Setter for Logo
             * 
             * @param {string} value 
             */
            SearchFoodRestaurantsResponse.prototype.setLogo = function (value) {
                this.logo = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            SearchFoodRestaurantsResponse.prototype.getName = function () {
                return this.name;
            };
        
            /**
             * Setter for Name
             * 
             * @param {string} value 
             */
            SearchFoodRestaurantsResponse.prototype.setName = function (value) {
                this.name = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            SearchFoodRestaurantsResponse.prototype.getFoodRestaurantId = function () {
                return this.foodRestaurantId;
            };
        
            /**
             * Setter for FoodRestaurantId
             * 
             * @param {string} value 
             */
            SearchFoodRestaurantsResponse.prototype.setFoodRestaurantId = function (value) {
                this.foodRestaurantId = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {double}
             */
            SearchFoodRestaurantsResponse.prototype.getSearchScore = function () {
                return this.searchScore;
            };
        
            /**
             * Setter for SearchScore
             * 
             * @param {double} value 
             */
            SearchFoodRestaurantsResponse.prototype.setSearchScore = function (value) {
                this.searchScore = value;
            };
        
            return SearchFoodRestaurantsResponse;
        }
    ]);

}(angular));
