/**
 * HealthOSLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of SideEffect
 *
 * @constructor
 */
angular.module('HealthOSLib')
    .factory('SideEffect', ['BaseModel',
        function (BaseModel) {
            var SideEffect = function (obj) {
                if (!obj) {
                    this.term = null;
                    this.count = null;
                    this.percent = null;
                } else {
                    this.term = obj.term;
                    this.count = obj.count;
                    this.percent = obj.percent;
                }
            }
    
            SideEffect.prototype = new BaseModel();
            SideEffect.prototype.constructor = SideEffect;
        
            /**
             * TODO: Write general description for this method
             *
             * @return {string}
             */
            SideEffect.prototype.getTerm = function () {
                return this.term;
            };
        
            /**
             * Setter for Term
             * 
             * @param {string} value 
             */
            SideEffect.prototype.setTerm = function (value) {
                this.term = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {int}
             */
            SideEffect.prototype.getCount = function () {
                return this.count;
            };
        
            /**
             * Setter for Count
             * 
             * @param {int} value 
             */
            SideEffect.prototype.setCount = function (value) {
                this.count = value;
            };
        
            /**
             * TODO: Write general description for this method
             *
             * @return {double}
             */
            SideEffect.prototype.getPercent = function () {
                return this.percent;
            };
        
            /**
             * Setter for Percent
             * 
             * @param {double} value 
             */
            SideEffect.prototype.setPercent = function (value) {
                this.percent = value;
            };
        
            return SideEffect;
        }
    ]);

}(angular));
